#!/bin/bash
#

user=`busybox whoami`
remote_server=$1

function usage()
{
    echo "ssh {remote_server} " 
    exit
}

function valid_ip()
{
    local  ip=$1
    local  stat=1
    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
    then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    echo $stat
}

[ -f "/home/${user}/.ssh/id_rsa.pub" ] && echo "对不起，您的帐号没有RSA密钥对，无法登陆目标服务器，请联系运维同学解决！" && exit
[ $# -ne 1 ] &&  usage
valid_result=`valid_ip ${remote_server}`
[ ${valid_result} -ne 0 ] && echo "IP地址非法！" && exit

info=`python /opt/ljops/apps/ljssh/get_info.py $user ${remote_server}`
if [[ "####" =~ ${info} ]]
then
    echo "对不起，您暂无权限登录服务器！"
    exit
fi
user=`echo "$info" | busybox awk -F"##" '{print $1}'`
hts=`echo "$info" | busybox awk -F"##"  '{print $2}' | busybox sed  -e 's/@/ /g'`
ts=`echo "$info" | busybox awk -F"##" '{print $3}'`

hosts=`echo "$info" | busybox awk -F"##"  '{print $2}' | busybox sed  -e 's/@/ /g'`
echo "hello, $user"
echo "Your time is $ts s"
if [[ ${hosts} =~ ${remote_server}  &&  "x${remote_server}" != "x"   ]] 
then
    echo "Connecting to ${remote_server}"
    python /opt/ljops/apps/ljssh/check_user.py ${user} ${remote_server}
    echo ${remote_server}
    ljssh -l ${user} ${remote_server}
else 
    echo "You only can login ($hts)"
    echo "which server do you want to login?"
    
    j=0
    for i in $hosts
    do
        ips=`echo $i | busybox cut -f 1 -d,`
        host_array[$j]=$ips
        echo "[$j]:$ips"
        j=$((j+1))
    done
    
    read -p "Enter your choice: " server_id
    case $server_id in
        [0-9]*)
            if [ "x${host_array[${server_id}]}" == "x" ]
            then
                echo "wrong option, exit"
                exit
            else 
                echo "Connecting to ${host_array[${server_id}]}"
                python /opt/ljops/apps/ljssh/check_user.py ${user} ${host_array[${server_id}]}
                ljssh -l $user ${host_array[${server_id}]}
            fi
        ;;
        *)
            echo "wrong option, exit"
            exit
        ;;
    esac
fi
